name:  proxy_collection
version: 1.2.0
description:  A simple set of proxy collection class utilities.
author: Simon Pai <simon.pai@gmail.com>
homepage: https://github.com/simonpai/dart-proxy-collection
